"""add ticker_created_at_index

Revision ID: 0466681724a9
Revises: 8d529cea8fbb
Create Date: 2026-02-04 09:16:35.137735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0466681724a9'
down_revision: Union[str, Sequence[str], None] = '8d529cea8fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ticker_created_at', 'index_prices_deribit', ['ticker', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_created_at', table_name='index_prices_deribit')
    # ### end Alembic commands ###
